name: Scheduler Test

on:
  schedule:
    - cron: '*/5 * * * *'
      timezone: "Europe/Madrid"

jobs:
  scheduler-test:
    runs-on: ubuntu-latest

    steps:
      - name: Scheduler heartbeat
        run: |
          echo "Scheduler works"
          date
